name: ğŸ­ Deploy CultGit

on:
  push:
    paths:
      - 'tools/culturenesshome/**'  # Solo cuando cambie esto
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v3
      
      - name: â” Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: ğŸ“¦ Install dependencies
        run: npm ci
        working-directory: ./tools/culturenesshome
      
      - name: ğŸ—ï¸ Build project
        run: npm run build
        working-directory: ./tools/culturenesshome
      
      - name: ğŸš€ Deploy to CultGit
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.CULTGIT_TOKEN }}  # Token para CultGit
          external_repository: BlancaStudio/CultGit
          publish_dir: ./tools/culturenesshome/dist
          keep_files: false
